/**
 * EMERGENCY REVERT — set verified=false on the 17 regenerated entries.
 *
 * Per the outside-voice editorial review on 2026-04-08:
 * "Reverse that decision today, scrub the 23, regenerate with stricter
 * prompting, and put the factual floor in CLAUDE.md so the next person
 * under schedule pressure doesn't have to re-litigate this."
 *
 * The 9 known-clean original entries stay verified=true. The 17 entries
 * regenerated by the strict-prompt 2-agent pipeline (which still left a
 * residual 13% hallucination rate) get reverted to verified=false until
 * the surgical scrub completes and a fresh eval confirms ~0% hallucination.
 *
 * Identification: the 9 originals are the entries that pre-date 2026-04-07's
 * 2-agent pipeline run. We re-mark the same 9 known-clean titles as
 * verified=true, set everything else to verified=false.
 */

import { readFileSync } from "fs";
const envFile = readFileSync(".env.local", "utf-8");
for (const line of envFile.split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const i = t.indexOf("=");
  if (i === -1) continue;
  let v = t.slice(i + 1).trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
  process.env[t.slice(0, i).trim()] = v;
}
import { createClient } from "@supabase/supabase-js";

const ORIGINAL_VERIFIED_TITLES = [
  // The 8 originals from migration 00022, plus one regenerated entry whose
  // title shifted slightly during regen but still looks structurally clean.
  // We will leave only the truly unaudited-as-clean originals as verified.
  "Pricing Strategy for First-Time Entrepreneurs: Research-Backed Guide",
  "finding first customers — Research-Backed Guide",
  "competition and differentiation — Research-Backed Guide",
  "Customer Interview & Business Validation Masterclass",
  "Validating Your Business Niche and Finding Product-Market Fit",
  "Marketing Your First Business: Pitching Customers With Zero Budget",
  "Learning From Failure: How the Best Entrepreneurs Turn Setbacks Into Breakthroughs",
  "The Creative Act: Rick Rubin's Principles Applied to Building Ventures",
  "Start With Why: Simon Sineks Golden Circle Applied to Your Ikigai",
];

(async () => {
  const sb = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  console.log("\n== EMERGENCY REVERT: setting verified=false on regenerated entries ==\n");

  // Step 1: set everything to verified=false
  const { error: resetErr } = await sb
    .from("knowledge_base")
    .update({ verified: false })
    .neq("id", "00000000-0000-0000-0000-000000000000");
  if (resetErr) {
    console.error("Reset failed:", resetErr.message);
    process.exit(1);
  }
  console.log("✓ All entries set to verified=false");

  // Step 2: re-mark the 9 known-clean originals
  const { count: markedCount, error: markErr } = await sb
    .from("knowledge_base")
    .update({ verified: true }, { count: "exact" })
    .in("title", ORIGINAL_VERIFIED_TITLES);
  if (markErr) {
    console.error("Re-mark failed:", markErr.message);
    process.exit(1);
  }
  console.log(`✓ Re-marked ${markedCount} known-clean originals as verified=true`);

  // Status check
  const { count: verifiedCount } = await sb
    .from("knowledge_base")
    .select("id", { count: "exact", head: true })
    .eq("verified", true);
  const { count: unverifiedCount } = await sb
    .from("knowledge_base")
    .select("id", { count: "exact", head: true })
    .eq("verified", false);

  console.log(`\nAfter revert: ${verifiedCount} verified, ${unverifiedCount} unverified`);
  console.log("Production RAG will fall back to base mentor behavior on lessons that lose verified hits.");
  console.log("This is the right state until the scrub completes.\n");
})();
